import Link from "next/link";
import AppShell from "@/components/period/AppShell";
import BottomNav from "@/components/period/BottomNav";
import StatusBar from "@/components/period/StatusBar";

function Day({ n, active, pink, yellow }: { n: number; active?: boolean; pink?: boolean; yellow?: boolean }) {
  return <div style={{ height:48, borderRadius:16, display:'grid', placeItems:'center', background: active ? 'var(--primary)' : yellow ? '#fff4c8' : pink ? '#ffe6f0' : 'white', color: active ? 'white' : 'var(--text)', border: active ? 'none' : '1px solid var(--border)', fontWeight:700 }}>{n}</div>;
}

export default function CalendarPage(){
  return <AppShell><StatusBar /><section className="screen-stack"><div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}><div><p className="label">Calendar</p><h1 className="page-title" style={{ marginTop:8 }}>May 2026</h1></div><Link href="/edit-period" className="ghost-button" style={{ width:140 }}>Edit period</Link></div><div className="desktop-two-col"><div className="hero-card stack"><div className="week-row">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d)=><div key={d} className="week-label">{d}</div>)}</div><div className="week-row"><Day n={1} pink /><Day n={2} pink /><Day n={3} pink /><Day n={4} active /><Day n={5} pink /><Day n={6} /><Day n={7} /></div><div className="week-row"><Day n={8} /><Day n={9} /><Day n={10} /><Day n={11} /><Day n={12} yellow /><Day n={13} yellow /><Day n={14} yellow /></div><div className="week-row"><Day n={15} /><Day n={16} /><Day n={17} /><Day n={18} /><Day n={19} /><Day n={20} /><Day n={21} /></div><div className="week-row"><Day n={22} /><Day n={23} /><Day n={24} /><Day n={25} /><Day n={26} /><Day n={27} /><Day n={28} /></div><div className="week-row"><Day n={29} /><Day n={30} /><Day n={31} /><div /><div /><div /><div /></div></div><div className="stack"><div className="metric-box"><p className="label" style={{ margin:0 }}>Legend</p><p className="page-subtitle" style={{ marginTop:8, fontSize:13 }}>Pink = period, yellow = ovulation window.</p></div><div className="metric-box"><p className="label" style={{ margin:0 }}>Selected day</p><h3 style={{ margin:'10px 0 0', fontSize:28, fontWeight:800 }}>May 4</h3><p className="page-subtitle" style={{ marginTop:8, fontSize:13 }}>Cycle day 4 is currently active.</p></div><div className="metric-box"><p className="label" style={{ margin:0 }}>Actions</p><div className="stack" style={{ marginTop:12 }}><Link href="/date/select" className="secondary-button">Select date</Link><Link href="/home" className="secondary-button">Back home</Link></div></div></div></div></section><BottomNav active="Calendar" /></AppShell>;
}
