import Link from "next/link";
import AppShell from "@/components/period/AppShell";
import BottomNav from "@/components/period/BottomNav";
import StatusBar from "@/components/period/StatusBar";

function Stat({ title, value, sub }: { title: string; value: string; sub: string }) {
  return <div className="metric-box"><p className="label" style={{ margin:0 }}>{title}</p><h3 style={{ margin:'10px 0 0', fontSize:28, fontWeight:800 }}>{value}</h3><p className="page-subtitle" style={{ margin:'6px 0 0', fontSize:14 }}>{sub}</p></div>;
}

export default function HomePage(){
  return <AppShell><StatusBar /><section className="screen-stack"><div className="profile-card"><div className="avatar">B</div><div><p className="label" style={{ margin:0 }}>Good morning</p><h1 className="page-title" style={{ marginTop:6, fontSize:28 }}>Bhim</h1></div></div><div className="desktop-two-col"><div className="hero-card stack"><div><p className="label">Today</p><h2 className="page-title" style={{ marginTop:8, fontSize:30 }}>4th day of period</h2><p className="page-subtitle" style={{ marginTop:10 }}>Your next ovulation window starts in about 11 days. Keep tracking symptoms and hydration for better predictions.</p></div><div className="cycle-ring" style={{ width:250, height:250 }}><div className="cycle-ring-inner"><div><p className="label" style={{ margin:0 }}>Current phase</p><div style={{ fontSize:24, fontWeight:800, marginTop:10 }}>Menstrual</div><p className="page-subtitle" style={{ margin:'8px 0 0', fontSize:14 }}>Cycle day 4</p></div></div></div></div><div className="stack"><div className="mini-grid"><Stat title="Period length" value="5 days" sub="Average" /><Stat title="Cycle length" value="28 days" sub="Typical" /></div><div className="card stack"><div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}><h2 style={{ margin:0, fontSize:22, fontWeight:800 }}>Quick actions</h2><span className="label">Today</span></div><Link href="/add-log" className="secondary-button">Add symptom log</Link><Link href="/calendar" className="secondary-button">Open calendar</Link><Link href="/tracker/log-count" className="secondary-button">See tracker</Link></div></div></div><div className="card stack"><div style={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}><h2 style={{ margin:0, fontSize:22, fontWeight:800 }}>Today’s plan</h2><span className="label">Quick</span></div><div className="task-row"><div><strong>Log symptoms</strong><p className="page-subtitle" style={{ margin:'4px 0 0', fontSize:13 }}>Track mood, weight, and temperature.</p></div><Link href="/add-log" className="ghost-button" style={{ width:96 }}>Open</Link></div><div className="task-row"><div><strong>Drink water</strong><p className="page-subtitle" style={{ margin:'4px 0 0', fontSize:13 }}>You have logged 800 ml today.</p></div><Link href="/water" className="ghost-button" style={{ width:96 }}>Track</Link></div><div className="task-row"><div><strong>View calendar</strong><p className="page-subtitle" style={{ margin:'4px 0 0', fontSize:13 }}>Check predictions and cycle dates.</p></div><Link href="/calendar" className="ghost-button" style={{ width:96 }}>View</Link></div></div></section><BottomNav active="Home" /></AppShell>;
}
